# Generated by Django 3.2.15 on 2022-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='textbox',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Type your message her', max_length=500),
        ),
    ]
