# Generated by Django 3.2.15 on 2022-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Type your message her', max_length=200),
        ),
    ]
