# Generated by Django 3.2.15 on 2022-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_contact_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query_type',
            field=models.IntegerField(choices=[(0, 'Question'), (1, 'Contribute')], default=0),
        ),
    ]
